use diff::Diff;
use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, PartialEq, Hash, Eq, Serialize, Deserialize, Diff)]
#[diff(attr(
    #[derive(Serialize, Deserialize)]
))]
pub enum KeyCode {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown,
}

impl Into<macroquad::input::KeyCode> for KeyCode {
    fn into(self: KeyCode) -> macroquad::input::KeyCode {
        match self {
            KeyCode::Space => macroquad::input::KeyCode::Space,
            KeyCode::Apostrophe => macroquad::input::KeyCode::Apostrophe,
            KeyCode::Comma => macroquad::input::KeyCode::Comma,
            KeyCode::Minus => macroquad::input::KeyCode::Minus,
            KeyCode::Period => macroquad::input::KeyCode::Period,
            KeyCode::Slash => macroquad::input::KeyCode::Slash,
            KeyCode::Key0 => macroquad::input::KeyCode::Key0,
            KeyCode::Key1 => macroquad::input::KeyCode::Key1,
            KeyCode::Key2 => macroquad::input::KeyCode::Key2,
            KeyCode::Key3 => macroquad::input::KeyCode::Key3,
            KeyCode::Key4 => macroquad::input::KeyCode::Key4,
            KeyCode::Key5 => macroquad::input::KeyCode::Key5,
            KeyCode::Key6 => macroquad::input::KeyCode::Key6,
            KeyCode::Key7 => macroquad::input::KeyCode::Key7,
            KeyCode::Key8 => macroquad::input::KeyCode::Key8,
            KeyCode::Key9 => macroquad::input::KeyCode::Key9,
            KeyCode::Semicolon => macroquad::input::KeyCode::Semicolon,
            KeyCode::Equal => macroquad::input::KeyCode::Equal,
            KeyCode::A => macroquad::input::KeyCode::A,
            KeyCode::B => macroquad::input::KeyCode::B,
            KeyCode::C => macroquad::input::KeyCode::C,
            KeyCode::D => macroquad::input::KeyCode::D,
            KeyCode::E => macroquad::input::KeyCode::E,
            KeyCode::F => macroquad::input::KeyCode::F,
            KeyCode::G => macroquad::input::KeyCode::G,
            KeyCode::H => macroquad::input::KeyCode::H,
            KeyCode::I => macroquad::input::KeyCode::I,
            KeyCode::J => macroquad::input::KeyCode::J,
            KeyCode::K => macroquad::input::KeyCode::K,
            KeyCode::L => macroquad::input::KeyCode::L,
            KeyCode::M => macroquad::input::KeyCode::M,
            KeyCode::N => macroquad::input::KeyCode::N,
            KeyCode::O => macroquad::input::KeyCode::O,
            KeyCode::P => macroquad::input::KeyCode::P,
            KeyCode::Q => macroquad::input::KeyCode::Q,
            KeyCode::R => macroquad::input::KeyCode::R,
            KeyCode::S => macroquad::input::KeyCode::S,
            KeyCode::T => macroquad::input::KeyCode::T,
            KeyCode::U => macroquad::input::KeyCode::U,
            KeyCode::V => macroquad::input::KeyCode::V,
            KeyCode::W => macroquad::input::KeyCode::W,
            KeyCode::X => macroquad::input::KeyCode::X,
            KeyCode::Y => macroquad::input::KeyCode::Y,
            KeyCode::Z => macroquad::input::KeyCode::Z,
            KeyCode::LeftBracket => macroquad::input::KeyCode::LeftBracket,
            KeyCode::Backslash => macroquad::input::KeyCode::Backslash,
            KeyCode::RightBracket => macroquad::input::KeyCode::RightBracket,
            KeyCode::GraveAccent => macroquad::input::KeyCode::GraveAccent,
            KeyCode::World1 => macroquad::input::KeyCode::World1,
            KeyCode::World2 => macroquad::input::KeyCode::World2,
            KeyCode::Escape => macroquad::input::KeyCode::Escape,
            KeyCode::Enter => macroquad::input::KeyCode::Enter,
            KeyCode::Tab => macroquad::input::KeyCode::Tab,
            KeyCode::Backspace => macroquad::input::KeyCode::Backspace,
            KeyCode::Insert => macroquad::input::KeyCode::Insert,
            KeyCode::Delete => macroquad::input::KeyCode::Delete,
            KeyCode::Right => macroquad::input::KeyCode::Right,
            KeyCode::Left => macroquad::input::KeyCode::Left,
            KeyCode::Down => macroquad::input::KeyCode::Down,
            KeyCode::Up => macroquad::input::KeyCode::Up,
            KeyCode::PageUp => macroquad::input::KeyCode::PageUp,
            KeyCode::PageDown => macroquad::input::KeyCode::PageDown,
            KeyCode::Home => macroquad::input::KeyCode::Home,
            KeyCode::End => macroquad::input::KeyCode::End,
            KeyCode::CapsLock => macroquad::input::KeyCode::CapsLock,
            KeyCode::ScrollLock => macroquad::input::KeyCode::ScrollLock,
            KeyCode::NumLock => macroquad::input::KeyCode::NumLock,
            KeyCode::PrintScreen => macroquad::input::KeyCode::PrintScreen,
            KeyCode::Pause => macroquad::input::KeyCode::Pause,
            KeyCode::F1 => macroquad::input::KeyCode::F1,
            KeyCode::F2 => macroquad::input::KeyCode::F2,
            KeyCode::F3 => macroquad::input::KeyCode::F3,
            KeyCode::F4 => macroquad::input::KeyCode::F4,
            KeyCode::F5 => macroquad::input::KeyCode::F5,
            KeyCode::F6 => macroquad::input::KeyCode::F6,
            KeyCode::F7 => macroquad::input::KeyCode::F7,
            KeyCode::F8 => macroquad::input::KeyCode::F8,
            KeyCode::F9 => macroquad::input::KeyCode::F9,
            KeyCode::F10 => macroquad::input::KeyCode::F10,
            KeyCode::F11 => macroquad::input::KeyCode::F11,
            KeyCode::F12 => macroquad::input::KeyCode::F12,
            KeyCode::F13 => macroquad::input::KeyCode::F13,
            KeyCode::F14 => macroquad::input::KeyCode::F14,
            KeyCode::F15 => macroquad::input::KeyCode::F15,
            KeyCode::F16 => macroquad::input::KeyCode::F16,
            KeyCode::F17 => macroquad::input::KeyCode::F17,
            KeyCode::F18 => macroquad::input::KeyCode::F18,
            KeyCode::F19 => macroquad::input::KeyCode::F19,
            KeyCode::F20 => macroquad::input::KeyCode::F20,
            KeyCode::F21 => macroquad::input::KeyCode::F21,
            KeyCode::F22 => macroquad::input::KeyCode::F22,
            KeyCode::F23 => macroquad::input::KeyCode::F23,
            KeyCode::F24 => macroquad::input::KeyCode::F24,
            KeyCode::F25 => macroquad::input::KeyCode::F25,
            KeyCode::Kp0 => macroquad::input::KeyCode::Kp0,
            KeyCode::Kp1 => macroquad::input::KeyCode::Kp1,
            KeyCode::Kp2 => macroquad::input::KeyCode::Kp2,
            KeyCode::Kp3 => macroquad::input::KeyCode::Kp3,
            KeyCode::Kp4 => macroquad::input::KeyCode::Kp4,
            KeyCode::Kp5 => macroquad::input::KeyCode::Kp5,
            KeyCode::Kp6 => macroquad::input::KeyCode::Kp6,
            KeyCode::Kp7 => macroquad::input::KeyCode::Kp7,
            KeyCode::Kp8 => macroquad::input::KeyCode::Kp8,
            KeyCode::Kp9 => macroquad::input::KeyCode::Kp9,
            KeyCode::KpDecimal => macroquad::input::KeyCode::KpDecimal,
            KeyCode::KpDivide => macroquad::input::KeyCode::KpDivide,
            KeyCode::KpMultiply => macroquad::input::KeyCode::KpMultiply,
            KeyCode::KpSubtract => macroquad::input::KeyCode::KpSubtract,
            KeyCode::KpAdd => macroquad::input::KeyCode::KpAdd,
            KeyCode::KpEnter => macroquad::input::KeyCode::KpEnter,
            KeyCode::KpEqual => macroquad::input::KeyCode::KpEqual,
            KeyCode::LeftShift => macroquad::input::KeyCode::LeftShift,
            KeyCode::LeftControl => macroquad::input::KeyCode::LeftControl,
            KeyCode::LeftAlt => macroquad::input::KeyCode::LeftAlt,
            KeyCode::LeftSuper => macroquad::input::KeyCode::LeftSuper,
            KeyCode::RightShift => macroquad::input::KeyCode::RightShift,
            KeyCode::RightControl => macroquad::input::KeyCode::RightControl,
            KeyCode::RightAlt => macroquad::input::KeyCode::RightAlt,
            KeyCode::RightSuper => macroquad::input::KeyCode::RightSuper,
            KeyCode::Menu => macroquad::input::KeyCode::Menu,
            KeyCode::Unknown => macroquad::input::KeyCode::Unknown,
        }
    }
}