[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
diff-struct = "0.5.3"
macroquad = "0.4.5"
nalgebra = "0.32.5"
rapier2d = "0.18.0"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
uuid = { version = "1.8.0", features = ["v4"] }

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[lib]
name = "game"
path = "src/lib.rs"


