[package]
name = "liquidators"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
diff-struct = "0.5.3"
macroquad = {git = "https://github.com/VoxanyNet/macroquad", rev = "659081936a0e32befc63169391b7cc5a85801470"}
nalgebra = {git = "https://github.com/VoxanyNet/nalgebra", rev = "c57d898ac19a01ac5ad2d6da5f98dea91257ac9e"}
rapier2d = { git = "https://github.com/VoxanyNet/rapier", rev = "54b56a9a72d223b407a01c97865067eaa3d5e0e4", features = ["serde-serialize"] }
serde = { version = "1.0.205", features = ["serde_derive"] }
lz4_flex = { version = "0.11", default-features = false }
ewebsock = "0.6.0"
gamelibrary = {git = "https://github.com/VoxanyNet/gamelibrary", rev = "23a803d5ec09e14efe731d47218cf29655070e32"}
#gamelibrary ={ path = "../gamelibrary"}
bitcode = { version = "0.6.0", features = ["serde"] }
rand = "0.8.5"
tungstenite = "0.23.0"
fxhash = "0.2.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
ears = {git="https://github.com/VoxanyNet/ears", rev = "dd2a11b664782c361cdc34fcc098814ed2dc5f76"}

[[bin]]
name = "updater"
path = "src/updater/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "editor-client"
path = "src/editor_client/main.rs"

[[bin]]
name = "editor-server"
path = "src/editor_server/main.rs"

[lib]
name = "liquidators_lib"
path = "src/lib.rs"

