[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diff-struct = "0.5.3"
glam = { version = "0.25.0", features = ["serde"] }
macroquad = "0.4.4"
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.197", features = ["serde_derive"] }
vector2d = "2.2.0"
