[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
deriving_via = "1.6.1"
diff-struct = "0.5.3"
glam = "0.26.0"
macroquad = "0.4.5"
deranged = { version = "0.3.9", default-features = false, features = [
    "powerfmt",
] }
time-core = "0.1.2"
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_millis = "0.1.1"
time = { version = "0.3.34", features = ["serde"] }
vector2d = "2.2.0"
serde_json = "1.0.114"
uuid = { version = "1.8.0", features = ["v4"] }

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[lib]
name = "game"
path = "src/lib.rs"


