[package]
name = "liquidators"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
diff-struct = "0.5.3"
macroquad = "0.4.5"
nalgebra = "0.32.5"
rapier2d = "0.18.0"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
uuid = { version = "1.8.0", features = ["v4"] }
lz4_flex = { version = "0.11", default-features = false }
ewebsock = "0.6.0"
tungstenite = "0.21.0"
#gamelibrary = {path = "../gamelibrary"}
gamelibrary = {git = "https://github.com/VoxanyNet/gamelibrary", rev = "202f70499147d7e379a71955d4a71f816a516764"}
serde-binary = "0.5.0"
bitcode = { version = "0.6.0", features = ["serde"] }
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["blocking"] }

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[lib]
name = "liquidators_lib"
path = "src/lib.rs"

